### ISSUE TITLE
Add nextcloud/coding-standard to composer.json

### ISSUE THREAD

**Issue by thlehmann-ionos** [nextcloud/app_template#66]
When creating an app from the template (also online app create wizard), the `composer cs` command will fail with warnings regarding the code style. It wants to enforce spaces where `.editorconfig` of NExtcloud expects tabs. The generated `Application.php` also violates the code style. Although the `.php-cs-fixer.dist.php` being checked in, the dependency is missing.

**Comment by provokateurin** [comment]
The dependency is present in https://github.com/nextcloud/app_template/blob/main/vendor-bin/cs-fixer/composer.json.
Are you able to execute `composer cs:fix` without any problems? It sounds like you didn't install the dependencies correctly.

Also there is no `.editorconfig` in this repo, are you maybe referring to https://github.com/nextcloud/server/blob/master/.editorconfig?

**Comment by thlehmann-ionos** [comment]
It turns it was only a missing `.php-cs-fixer.dist.php`, not the missing `require-dev`.

> Also there is no .editorconfig in this repo, are you maybe referring to https://github.com/nextcloud/server/blob/master/.editorconfig?

Yes.

Nothing to do. Close. Sorry for the noise.

**Comment by provokateurin** [comment]
> It turns it was only a missing .php-cs-fixer.dist.php, not the missing require-dev.

But the file is in this repo? I'm not sure I understand what went wrong here.

**Comment by thlehmann-ionos** [comment]
It was missing in the Repo I created from the downloaded app boilerplate zip. It's present in the template repo and it was present in the .zip. It must have been a mistake when copying the files over from the .zip. My bad.
